// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA76RvegWrKHumeHAsgfhWWHXCNvy8XRsk',
    appId: '1:53453936657:web:edf0efcea3b0d726f9b9b0',
    messagingSenderId: '53453936657',
    projectId: 'notes-app-34b74',
    authDomain: 'notes-app-34b74.firebaseapp.com',
    storageBucket: 'notes-app-34b74.appspot.com',
    measurementId: 'G-3W4DWGRL03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFatcVgazueKjiArJyVPoKhs8rh7LY0n4',
    appId: '1:53453936657:android:4fd84fcefba51459f9b9b0',
    messagingSenderId: '53453936657',
    projectId: 'notes-app-34b74',
    storageBucket: 'notes-app-34b74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEXFD5OUdqESp1Bcjx4guKdvlFXTeB0us',
    appId: '1:53453936657:ios:6bbc2be9cf4d72c0f9b9b0',
    messagingSenderId: '53453936657',
    projectId: 'notes-app-34b74',
    storageBucket: 'notes-app-34b74.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEXFD5OUdqESp1Bcjx4guKdvlFXTeB0us',
    appId: '1:53453936657:ios:da0fc91f2a8aae4ff9b9b0',
    messagingSenderId: '53453936657',
    projectId: 'notes-app-34b74',
    storageBucket: 'notes-app-34b74.appspot.com',
    iosBundleId: 'com.example.notesApp.RunnerTests',
  );
}
